---
title: "Soil Temps"
author: "Coleson Kastelic"
date: "October 3, 2019"
output: html_document
---
Libraries and Setting timezone for US/Denver to clear strptime warning
```{r,echo=FALSE, message=FALSE, results='hide'}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(readr)
Sys.setenv(TZ='America/Denver')
```

2013-2014 Data Cleaning/Formatting
```{r,echo=FALSE,message=FALSE,results='hide'}
Abla.L.2013_14<- read_csv('CO_soil_temps/2013-2014/TS2_13_6A_2AF15921_Fall13-June14.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.L.2013_14$Date.Time<-format(strptime(Abla.L.2013_14$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.L.2013_14$Date.Time<-as_datetime(ymd_hm(Abla.L.2013_14$Date.Time))
Abla.L.2013_14<-Abla.L.2013_14 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.L')

Pipo.L.2013_14<- read_csv('CO_soil_temps/2013-2014/TS4_13_d2_2AFDAC21_Fall13-June14_soilT_2013-14.csv',skip=13)%>%
  rename('Temp'='Temperature','Date.Time'='DateTime') %>%
  select(-c(Unit,Light))
Pipo.L.2013_14$Date.Time<-format(strptime(Pipo.L.2013_14$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.2013_14$Date.Time<-as_datetime(ymd_hm(Pipo.L.2013_14$Date.Time))
Pipo.L.2013_14<-Pipo.L.2013_14 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L')

No.Location.1.2013_15<- read_csv('CO_soil_temps/2013-2014/undownloaded-TS1_13_B9_Fall13-June14_2013-14.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
No.Location.1.2013_15$Date.Time<-format(strptime(No.Location.1.2013_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
No.Location.1.2013_15$Date.Time<-as_datetime(ymd_hm(No.Location.1.2013_15$Date.Time))
No.Location.1.2013_15<-No.Location.1.2013_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='No.Plot')

No.Location.2.2013_15<- read_csv('CO_soil_temps/2013-2014/TS3_13_81_2AE2FE21_Fall13-June14.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
No.Location.2.2013_15$Date.Time<-format(strptime(No.Location.2.2013_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
No.Location.2.2013_15$Date.Time<-as_datetime(ymd_hm(No.Location.2.2013_15$Date.Time))
No.Location.2.2013_15<-No.Location.2.2013_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='No.Plot')
```

2014-2015 Data Cleaning/Formating
```{r,echo=FALSE, message=FALSE, results='hide'}
#PIPO Plots
Pipo.H.E.2014_15 <- read_csv("CO_soil_temps/2014-2015/T11L_14_PIPO-H-E_091314-XXXXXX_soil.csv",skip=13) %>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.E.2014_15$Date.Time<-format(strptime(Pipo.H.E.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.E.2014_15$Date.Time<-as_datetime(ymd_hm(Pipo.H.E.2014_15$Date.Time))
Pipo.H.E.2014_15<-Pipo.H.E.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.E')

Pipo.H.B.2014_15 <- read_csv('CO_soil_temps/2014-2015/T49L_14_PIPO-H-B_091314-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.B.2014_15$Date.Time<-format(strptime(Pipo.H.B.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.B.2014_15$Date.Time<-as_datetime(ymd_hm(Pipo.H.B.2014_15$Date.Time))
Pipo.H.B.2014_15<-Pipo.H.B.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.B')

Pipo.L.C.2014_15 <- read_csv('CO_soil_temps/2014-2015/T50L_14_PIPO-L-C_062014-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.C.2014_15$Date.Time<-format(strptime(Pipo.L.C.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.C.2014_15$Date.Time<-as_datetime(ymd_hm(Pipo.L.C.2014_15$Date.Time))
Pipo.L.C.2014_15<-Pipo.L.C.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.C')

Pipo.L.D.2014_15 <- read_csv('CO_soil_temps/2014-2015/T59L_14_PIPO-L-D_070314-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.D.2014_15$Date.Time<-format(strptime(Pipo.L.D.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.D.2014_15$Date.Time<-as_datetime(ymd_hm(Pipo.L.D.2014_15$Date.Time))
Pipo.L.D.2014_15<-Pipo.L.D.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.D')

Pipo.L.A.2014_15 <- read_csv('CO_soil_temps/2014-2015/T63L_14_PIPO-L-A_091314-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.A.2014_15$Date.Time<-format(strptime(Pipo.L.A.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.A.2014_15$Date.Time<-as_datetime(ymd_hm(Pipo.L.A.2014_15$Date.Time))
Pipo.L.A.2014_15<-Pipo.L.A.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.A') 

#POTR Plots
Potr.H.B.2014_15 <- read_csv('CO_soil_temps/2014-2015/T28L_14_POTR-H-B_070314-063015_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.B.2014_15$Date.Time<-format(strptime(Potr.H.B.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.B.2014_15$Date.Time<-as_datetime(ymd_hm(Potr.H.B.2014_15$Date.Time))
Potr.H.B.2014_15<-Potr.H.B.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.B')

Potr.H.A.2014_15 <- read_csv('CO_soil_temps/2014-2015/T45L_14_POTR-H-A_062014-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.A.2014_15$Date.Time<-format(strptime(Potr.H.A.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.A.2014_15$Date.Time<-as_datetime(ymd_hm(Potr.H.A.2014_15$Date.Time))
Potr.H.A.2014_15<-Potr.H.A.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.A') 

#ABLA Plots
Abla.H.D.2014_15 <- read_csv('CO_soil_temps/2014-2015/T22L_14_ABLA-H-D_070314-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.D.2014_15$Date.Time<-format(strptime(Abla.H.D.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.D.2014_15$Date.Time<-as_datetime(ymd_hm(Abla.H.D.2014_15$Date.Time))
Abla.H.D.2014_15 <- Abla.H.D.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.D') 

Abla.L.B.2014_15 <- read_csv('CO_soil_temps/2014-2015/T23L_14_ABLA-L-B_062014-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.L.B.2014_15$Date.Time<-format(strptime(Abla.L.B.2014_15$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.L.B.2014_15$Date.Time<-as_datetime(ymd_hm(Abla.L.B.2014_15$Date.Time))
Abla.L.B.2014_15<-Abla.L.B.2014_15 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.L.D')

Y2014_15.Soil.Temp<-rbind.data.frame(Abla.H.D.2014_15,Abla.L.B.2014_15,Pipo.H.B.2014_15,Pipo.H.E.2014_15,Pipo.L.A.2014_15,Pipo.L.C.2014_15,Pipo.L.D.2014_15,Potr.H.A.2014_15,Potr.H.B.2014_15)
```

2014-2015 Histogram/Graphs
```{r}

```

2015-2016 Cleaning/Formating
```{r,echo=FALSE, message=FALSE, results='hide'}
#PIPO
Pipo.H.B.2015_16 <- read_csv('CO_soil_temps/2015-2016/T32L_14_PIPO-H-B_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.B.2015_16$Date.Time<-format(strptime(Pipo.H.B.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.B.2015_16$Date.Time<-as_datetime(ymd_hm(Pipo.H.B.2015_16$Date.Time))
Pipo.H.B.2015_16<-Pipo.H.B.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.B')

Pipo.H.E.2015_16<- read_csv('CO_soil_temps/2015-2016/T36L_14_PIPO-H-E_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.E.2015_16$Date.Time<-format(strptime(Pipo.H.E.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.E.2015_16$Date.Time<-as_datetime(ymd_hm(Pipo.H.E.2015_16$Date.Time))
Pipo.H.E.2015_16<-Pipo.H.E.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.E')

Pipo.L.C.2015_16<- read_csv('CO_soil_temps/2015-2016/T50L_14_PIPO-L-C_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.C.2015_16$Date.Time<-format(strptime(Pipo.L.C.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.C.2015_16$Date.Time<-as_datetime(ymd_hm(Pipo.L.C.2015_16$Date.Time))
Pipo.L.C.2015_16<-Pipo.L.C.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.C')

Pipo.L.A.2015_16<- read_csv('CO_soil_temps/2015-2016/T57L_14_PIPO-L-A_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.A.2015_16$Date.Time<-format(strptime(Pipo.L.A.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.A.2015_16$Date.Time<-as_datetime(ymd_hm(Pipo.L.A.2015_16$Date.Time))
Pipo.L.A.2015_16<-Pipo.L.A.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.A')

#Collected in 2017
Pipo.L.D.2015_16<- read_csv('CO_soil_temps/2015-2016/TS3_13_PIPO-L-D_092415-XXXXXX_soil_from2015butcollected2017.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.D.2015_16$Date.Time<-format(strptime(Pipo.L.D.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.D.2015_16$Date.Time<-as_datetime(ymd_hm(Pipo.L.D.2015_16$Date.Time))
Pipo.L.D.2015_16<-Pipo.L.D.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.D')

#POTR
Potr.H.A.2015_16<- read_csv('CO_soil_temps/2015-2016/T39L_14_POTR-H-A_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.A.2015_16$Date.Time<-format(strptime(Potr.H.A.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.A.2015_16$Date.Time<-as_datetime(ymd_hm(Potr.H.A.2015_16$Date.Time))
Potr.H.A.2015_16<-Potr.H.A.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.A')

Potr.H.B.2015_16<- read_csv('CO_soil_temps/2015-2016/T4L_14_POTR-H-B_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.B.2015_16$Date.Time<-format(strptime(Potr.H.B.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.B.2015_16$Date.Time<-as_datetime(ymd_hm(Potr.H.B.2015_16$Date.Time))
Potr.H.B.2015_16<-Potr.H.B.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.B')

Potr.L.C.2015_16<- read_csv('CO_soil_temps/2015-2016/T18L_14_POTR-L-C_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.L.C.2015_16$Date.Time<-format(strptime(Potr.L.C.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.L.C.2015_16$Date.Time<-as_datetime(ymd_hm(Potr.L.C.2015_16$Date.Time))
Potr.L.C.2015_16<-Potr.L.C.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.L.C')

#ABLA
Abla.L.B.2015_16<- read_csv('CO_soil_temps/2015-2016/T14L_14_ABLA-L-B_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.L.B.2015_16$Date.Time<-format(strptime(Abla.L.B.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.L.B.2015_16$Date.Time<-as_datetime(ymd_hm(Abla.L.B.2015_16$Date.Time))
Abla.L.B.2015_16<-Abla.L.B.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.L.B')

Abla.H.A.2015_16<- read_csv('CO_soil_temps/2015-2016/T22L_14_ABLA-H-A_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.A.2015_16$Date.Time<-format(strptime(Abla.H.A.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.A.2015_16$Date.Time<-as_datetime(ymd_hm(Abla.H.A.2015_16$Date.Time))
Abla.H.A.2015_16<-Abla.H.A.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.A')

Abla.H.D.2015_16<- read_csv('CO_soil_temps/2015-2016/T23L_14_ABLA-H-D_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.D.2015_16$Date.Time<-format(strptime(Abla.H.D.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.D.2015_16$Date.Time<-as_datetime(ymd_hm(Abla.H.D.2015_16$Date.Time))
Abla.H.D.2015_16<-Abla.H.D.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.D')

Abla.H.C.2015_16<- read_csv('CO_soil_temps/2015-2016/T30L_14_ABLA-H-C_082515-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.C.2015_16$Date.Time<-format(strptime(Abla.H.C.2015_16$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.C.2015_16$Date.Time<-as_datetime(ymd_hm(Abla.H.C.2015_16$Date.Time))
Abla.H.C.2015_16<-Abla.H.C.2015_16 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.C')

Y2015_16.Soil.Temp<-rbind.data.frame(Abla.H.A.2015_16,Abla.H.C.2015_16,Abla.H.D.2015_16,Abla.L.B.2015_16,Potr.H.A.2015_16,Potr.H.B.2015_16,Potr.L.C.2015_16,Pipo.H.B.2015_16,Pipo.H.E.2015_16,Pipo.L.A.2015_16,Pipo.L.C.2015_16,Pipo.L.D.2015_16)
```

2015-2016 Histogram/Graphs
```{r}

```

2016-2017 Data Cleaning/Formatting
```{r,echo=FALSE, message=FALSE, results='hide'}
#PIPO
Pipo.H.B.2016_17<- read_csv('CO_soil_temps/2016-2017/T40L_14_PIPO-H-B_090416-070717_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.B.2016_17$Date.Time<-format(strptime(Pipo.H.B.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.B.2016_17$Date.Time<-as_datetime(ymd_hm(Pipo.H.B.2016_17$Date.Time))
Pipo.H.B.2016_17<-Pipo.H.B.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.B')

Pipo.H.E.2016_17<- read_csv('CO_soil_temps/2016-2017/T41L_14_PIPO-H-E_090416-070717_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.E.2016_17$Date.Time<-format(strptime(Pipo.H.E.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.E.2016_17$Date.Time<-as_datetime(ymd_hm(Pipo.H.E.2016_17$Date.Time))
Pipo.H.E.2016_17<-Pipo.H.E.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.E')

Pipo.L.C.2016_17<- read_csv('CO_soil_temps/2016-2017/T54L_14_PIPO-L-C_090416-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.C.2016_17$Date.Time<-format(strptime(Pipo.L.C.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.C.2016_17$Date.Time<-as_datetime(ymd_hm(Pipo.L.C.2016_17$Date.Time))
Pipo.L.C.2016_17<-Pipo.L.C.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.C')

Pipo.L.A.2016_17<- read_csv('CO_soil_temps/2016-2017/T61L_14_PIPO-L-A_090416-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.A.2016_17$Date.Time<-format(strptime(Pipo.L.A.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.A.2016_17$Date.Time<-as_datetime(ymd_hm(Pipo.L.A.2016_17$Date.Time))
Pipo.L.A.2016_17<-Pipo.L.A.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.A')

#POTR
Potr.L.D.2016_17<- read_csv('CO_soil_temps/2016-2017/T43_14_Potr-L-D_090416-070717_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.L.D.2016_17$Date.Time<-format(strptime(Potr.L.D.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.L.D.2016_17$Date.Time<-as_datetime(ymd_hm(Potr.L.D.2016_17$Date.Time))
Potr.L.D.2016_17<-Potr.L.D.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.L.D')

Potr.H.A.2016_17<- read_csv('CO_soil_temps/2016-2017/T49L_14_Potr-H-A_090316-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.A.2016_17$Date.Time<-format(strptime(Potr.H.A.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.A.2016_17$Date.Time<-as_datetime(ymd_hm(Potr.H.A.2016_17$Date.Time))
Potr.H.A.2016_17<-Potr.H.A.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.A')

Potr.H.B.2016_17<- read_csv('CO_soil_temps/2016-2017/T63L_14_Potr-H-B_090316-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.B.2016_17$Date.Time<-format(strptime(Potr.H.B.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.B.2016_17$Date.Time<-as_datetime(ymd_hm(Potr.H.B.2016_17$Date.Time))
Potr.H.B.2016_17<-Potr.H.B.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.B')

#ABLA
Abla.H.C.2016_17<- read_csv('CO_soil_temps/2016-2017/T16L_14_ABLA-H-C_090316-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.C.2016_17$Date.Time<-format(strptime(Abla.H.C.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.C.2016_17$Date.Time<-as_datetime(ymd_hm(Abla.H.C.2016_17$Date.Time))
Abla.H.C.2016_17<-Abla.H.C.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.C')

Abla.L.B.2016_17<- read_csv('CO_soil_temps/2016-2017/T20L_14_ABLA-L-B_090316-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.L.B.2016_17$Date.Time<-format(strptime(Abla.L.B.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.L.B.2016_17$Date.Time<-as_datetime(ymd_hm(Abla.L.B.2016_17$Date.Time))
Abla.L.B.2016_17<-Abla.L.B.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.L.B')

Abla.H.A.2016_17<- read_csv('CO_soil_temps/2016-2017/T46L_14_ABLA-H-A_090316-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.A.2016_17$Date.Time<-format(strptime(Abla.H.A.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.A.2016_17$Date.Time<-as_datetime(ymd_hm(Abla.H.A.2016_17$Date.Time))
Abla.H.A.2016_17<-Abla.H.A.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.A')

Abla.H.D.2016_17<- read_csv('CO_soil_temps/2016-2017/TS1_13_ABLA-H-D_090316-070617_soil_ranover.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Abla.H.D.2016_17$Date.Time<-format(strptime(Abla.H.D.2016_17$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Abla.H.D.2016_17$Date.Time<-as_datetime(ymd_hm(Abla.H.D.2016_17$Date.Time))
Abla.H.D.2016_17<-Abla.H.D.2016_17 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Abla.H.D')

Y2016_17.Soil.Temp<-rbind.data.frame(Pipo.H.B.2016_17,Pipo.H.E.2016_17,Pipo.L.A.2016_17,Pipo.L.C.2016_17,Potr.H.A.2016_17,Potr.H.B.2016_17,Potr.L.D.2016_17,Abla.H.C.2016_17,Abla.H.A.2016_17,Abla.H.D.2016_17,Abla.L.B.2016_17)
```

2016-2017 Histogram/Graphs
```{r}

```

2018-2019 Data Cleaning/Formatting
```{r,echo=FALSE,message=FALSE,results='hide'}
#PIPO
Pipo.L.C.2018_19<- read_csv('CO_soil_temps/2018-2019/T39L_14_PIPO-L-C_090718-XXXXXX_soil_found on soil surface chewed.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.C.2018_19$Date.Time<-format(strptime(Pipo.L.C.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.C.2018_19$Date.Time<-as_datetime(ymd_hm(Pipo.L.C.2018_19$Date.Time))
Pipo.L.C.2018_19<-Pipo.L.C.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.C')

Pipo.H.B.2018_19<- read_csv('CO_soil_temps/2018-2019/T41L_14_PIPO-H-B_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.B.2018_19$Date.Time<-format(strptime(Pipo.H.B.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.B.2018_19$Date.Time<-as_datetime(ymd_hm(Pipo.H.B.2018_19$Date.Time))
Pipo.H.B.2018_19<-Pipo.H.B.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.B')

Pipo.H.E.2018_19<- read_csv('CO_soil_temps/2018-2019/T53L_14_PIPO-H-E_090718-XXXXXX_soil_found on soil surface chewed.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.H.E.2018_19$Date.Time<-format(strptime(Pipo.H.E.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.H.E.2018_19$Date.Time<-as_datetime(ymd_hm(Pipo.H.E.2018_19$Date.Time))
Pipo.H.E.2018_19<-Pipo.H.E.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.H.E')

Pipo.L.D.2018_19<- read_csv('CO_soil_temps/2018-2019/T48L_14_PIPO-L-D_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Pipo.L.D.2018_19$Date.Time<-format(strptime(Pipo.L.D.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Pipo.L.D.2018_19$Date.Time<-as_datetime(ymd_hm(Pipo.L.D.2018_19$Date.Time))
Pipo.L.D.2018_19<-Pipo.L.D.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Pipo.L.D')

#POTR
Potr.H.A.2018_19<- read_csv('CO_soil_temps/2018-2019/T33L_14_POTR-H-A_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.A.2018_19$Date.Time<-format(strptime(Potr.H.A.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.A.2018_19$Date.Time<-as_datetime(ymd_hm(Potr.H.A.2018_19$Date.Time))
Potr.H.A.2018_19<-Potr.H.A.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.A')

Potr.H.D.2018_19<- read_csv('CO_soil_temps/2018-2019/T38L_14_POTR-H-D_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.D.2018_19$Date.Time<-format(strptime(Potr.H.D.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.D.2018_19$Date.Time<-as_datetime(ymd_hm(Potr.H.D.2018_19$Date.Time))
Potr.H.D.2018_19<-Potr.H.D.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.D')

Potr.L.D.2018_19<- read_csv('CO_soil_temps/2018-2019/T43L_14_POTR-L-D_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.L.D.2018_19$Date.Time<-format(strptime(Potr.L.D.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.L.D.2018_19$Date.Time<-as_datetime(ymd_hm(Potr.L.D.2018_19$Date.Time))
Potr.L.D.2018_19<-Potr.L.D.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.L.D')

Potr.H.E.2018_19<- read_csv('CO_soil_temps/2018-2019/T49L_14_POTR-H-E_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.E.2018_19$Date.Time<-format(strptime(Potr.H.E.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.E.2018_19$Date.Time<-as_datetime(ymd_hm(Potr.H.E.2018_19$Date.Time))
Potr.H.E.2018_19<-Potr.H.E.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.E')

Potr.H.B.2018_19<- read_csv('CO_soil_temps/2018-2019/T63L_14_POTR-H-B_090718-XXXXXX_soil.csv',skip=13)%>%
  rename('Temp'='Value','Date.Time'='Date/Time') %>%
  select(-c(Unit))
Potr.H.B.2018_19$Date.Time<-format(strptime(Potr.H.B.2018_19$Date.Time, '%m/%d/%y %I:%M:%S %p'), format='%Y/%m/%d %H:%M %p')
Potr.H.B.2018_19$Date.Time<-as_datetime(ymd_hm(Potr.H.B.2018_19$Date.Time))
Potr.H.B.2018_19<-Potr.H.B.2018_19 %>%
  mutate(Year=year(Date.Time))%>%
  mutate(Month=month(Date.Time))%>%
  mutate(Day=day(Date.Time)) %>%
  mutate(Hour=hour(Date.Time)) %>%
  mutate(DOY=yday(Date.Time)) %>%
  mutate(Plot='Potr.H.B')

Y2018_19.Soil.Temp<-rbind.data.frame(Pipo.H.B.2018_19,Pipo.H.E.2018_19,Pipo.L.C.2018_19,Pipo.L.D.2018_19,Potr.H.A.2018_19,Potr.H.B.2018_19,Potr.H.D.2018_19,Potr.H.E.2018_19,Potr.L.D.2018_19)
```

Testing Chunk
```{r}

```